[2024.07.31] feat/#11-mypage-postList >> 쇼핑 메인페이지 백앤드와 연동
today-space/today-space-front pull request #20
Opened 2024-07-31 10:41 UTC by jdusw

## #️⃣ 11

> #11
> Close #11

## 📑 작업 내용
> - 쇼핑 메인페이지 백앤드와 연동

## 💭 리뷰 요구사항(선택)
> 주석 부분은 추후에 지우도록 하겠습니다

2024-07-31 10:51 UTC, jdusw commented on src/App.js
> +import Product from "./components/Product";
p5: import가 잘못되었습니다, 주석과 함께 지우겠습니다

2024-08-01 01:18 UTC, ryurbsgks5114 requested changes

2024-08-01 01:18 UTC, ryurbsgks5114 commented on src/components/Product.js
> +    if (token) {
P5: 토큰이 있는 경우 즉, 로그인 된 상태에서만 fetchProducts() 함수를 실행하는데 상품 조회 부분은 로그인하지 않아도 조회 가능한 걸로 알고 있습니다.

2024-08-01 01:33 UTC, ysy56 commented on src/components/Product.js
> +    if (token) {
P5 : 해당 의견은 저도 동의합니다. 마이페이지 부분을 제외한 조회 부분은 로그인 여부와 상관없이 조회 가능합니다!

2024-08-01 01:59 UTC, ryurbsgks5114 approved these changes

2024-08-01 01:59 UTC, merged